require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Layout/LineLength:
  Max: 90

RSpec/DescribeMethod:
  Exclude:
    - 'spec/*.rb'

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/*.rb'

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false
