module JSON
  module Patch
    module Operation
      def self.new: (Hash[Symbol | String, untyped] raw_operation) -> Base

      class Base
        @raw: Hash[Symbol, untyped]

        def initialize: (Hash[Symbol | String, untyped]) -> void

        def call: (TargetDocument _document) -> void

        def to_json: (*untyped) -> String

        private

        def fetch_member: (Symbol key, ?allow_nil: bool) -> untyped
      end

      class Add < Base
        def call: (TargetDocument document) -> untyped
      end

      class Remove < Base
        def call: (TargetDocument document) -> untyped
      end

      class Replace < Base
        def call: (TargetDocument document) -> untyped
      end

      class Move < Base
        def call: (TargetDocument document) -> untyped
      end

      class Copy < Base
        include Duplicate

        def call: (TargetDocument document) -> untyped
      end

      class Test < Base
        def call: (TargetDocument document) -> (nil | untyped)
      end

      private

      def self.determine_operation_class: (String) -> (
        singleton(Add) |
        singleton(Copy) |
        singleton(Move) |
        singleton(Remove) |
        singleton(Replace) |
        singleton(Test)
      )
    end
  end
end
