module JSON
  module Patch
    class Document
      class Builder
        @operations: Array[Operation::Base]

        attr_reader operations: Array[Operation::Base]

        def initialize: () -> void

        def add: (String path, value: untyped) -> void

        def copy: (from: String, path: String) -> void

        def move: (from: String, path: String) -> void

        def remove: (String path) -> void

        def replace: (String path, value: untyped) -> void

        def test: (String path, value: untyped) -> void
      end
    end
  end
end
