module JSON
  module Patch
    class Document
      class Builder
        @operations: Array[Hash[Symbol, untyped]]

        attr_reader operations: Array[Hash[Symbol, untyped]]

        def initialize: () -> void

        def add: (String path, value: untyped) -> untyped

        def copy: (from: String, path: String) -> untyped

        def move: (from: String, path: String) -> untyped

        def remove: (String path) -> untyped

        def replace: (String path, value: untyped) -> untyped

        def test: (String path, value: untyped) -> untyped
      end
    end
  end
end
