name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.3"
          - "3.2"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: find ruby version
      id: find
      run: echo ruby_version=$(ruby -v | grep -oP "\d\.\d\.\d") >> $GITHUB_OUTPUT

    - name: echo ruby version
      run: echo ${{ steps.find.outputs.ruby_version }}

    - name: Install RBS collection
      run: bundle exec rbs collection install
      if: steps.find.outputs.ruby_version >= '3.3.2'

    - name: Run the default task
      run: bundle exec rake
